### ISSUE TITLE
Expose creation and update timestamp in get config APIs

### ISSUE THREAD

**Issue by GurtejSohi** [hypertrace/config-service#25]
## Use Case
The client may be interested in the creation and/or update timestamp for config that it is dealing with. For example, client may want to sort all the configs based on the creation timestamp.

For this, we need to expose the creation and update timestamp in `GetConfig` and `GetAllConfigs` API.

## Proposal
We can add 2 extra fields in `GetConfigResponse` which takes care of the `GetConfig` API:
```
message GetConfigResponse {
  google.protobuf.Value config = 1;
  int64 creation_timestamp = 2; // new field
  int64 update_timestamp = 3;  // new field
}
```

We can add 2 extra fields in `ContextSpecificConfig` which takes care of the `GetAllConfigs` API:
```
message GetAllConfigsResponse {
  repeated ContextSpecificConfig context_specific_configs = 1;
}

message ContextSpecificConfig {
  string context = 1;
  google.protobuf.Value config = 2;
  int64 creation_timestamp = 3; // new field
  int64 update_timestamp = 4;  // new field
}
```

From implementation perspective, we'll now have to call `getConfig` while upserting any config so as to get the `creationTimestamp` for that config.

**Comment by aaron-steinfeld** [comment]
Seems right to me. We could add them on the upsert response too, but I'm fine ignoring that until there's a use case.
